/*
 * Copyright 2016-2017 the original author or authors.
 */
package pan.glenn.codegen.generator.util;

import org.mybatis.generator.api.dom.java.*;
import org.mybatis.generator.api.dom.xml.TextElement;
import org.mybatis.generator.api.dom.xml.XmlElement;
import org.mybatis.generator.config.MergeConstants;
import pan.glenn.codegen.context.DomainConfig;
import pan.glenn.codegen.context.DomainField;
import pan.glenn.codegen.context.GlobalConfig;
import pan.glenn.codegen.util.StringUtil;

import java.util.Date;

/**
 * Created by PanYunFeng on 2016/4/17.
 */
public class GlennCommentGenerator {

    private GlennCommentGenerator() {
        super();
    }

    public static void addJavaFileComment(CompilationUnit compilationUnit) {
        // add no file level comments by default
        return;
    }

    /**
     * Adds a suitable comment to warn users that the element was generated, and
     * when it was generated.
     */
    public static void addComment(XmlElement xmlElement) {
        if (GlobalConfig.getString("suppress.all.comments") != null) {
            return;
        }

        xmlElement.addElement(new TextElement("<!--")); //$NON-NLS-1$

        StringBuilder sb = new StringBuilder();
        sb.append("  WARNING - "); //$NON-NLS-1$
        sb.append(MergeConstants.NEW_ELEMENT_TAG);
        xmlElement.addElement(new TextElement(sb.toString()));
        xmlElement
                .addElement(new TextElement(
                        "  This element is automatically generated by MyBatis Generator, do not modify.")); //$NON-NLS-1$

        String s = getDateString();
        if (s != null && s.length() > 0) {
            sb.setLength(0);
            sb.append("  This element was generated on "); //$NON-NLS-1$
            sb.append(s);
            sb.append('.');
            xmlElement.addElement(new TextElement(sb.toString()));
        }

        xmlElement.addElement(new TextElement("-->")); //$NON-NLS-1$
    }

    public static void addRootComment(XmlElement rootElement) {
        // add no document level comments by default
        return;
    }

    /**
     * This method adds the custom javadoc tag for. You may do nothing if you do
     * not wish to include the Javadoc tag - however, if you do not include the
     * Javadoc tag then the Java merge capability of the eclipse plugin will
     * break.
     *
     * @param javaElement
     *            the java element
     */
    protected static void addJavadocTag(JavaElement javaElement,
                                 boolean markAsDoNotDelete) {
//        javaElement.addJavaDocLine(" *"); //$NON-NLS-1$
//        StringBuilder sb = new StringBuilder();
//        sb.append(" * "); //$NON-NLS-1$
//        sb.append(MergeConstants.NEW_ELEMENT_TAG);
//        if (markAsDoNotDelete) {
//            sb.append(" do_not_delete_during_merge"); //$NON-NLS-1$
//        }
//        String s = getDateString();
//        if (s != null && s.length() > 0) {
//            sb.append(' ');
//            sb.append(s);
//        }
//        javaElement.addJavaDocLine(sb.toString());
    }

    /**
     * This method returns a formated date string to include in the Javadoc tag
     * and XML comments. You may return null if you do not want the date in
     * these documentation elements.
     *
     * @return a string representing the current timestamp, or null
     */
    protected static String getDateString() {
        if (GlobalConfig.getString("suppress.date") != null) {
            return null;
        } else {
            return new Date().toString();
        }
    }

    /**
     *
     * @param innerClass
     * @param domainConfig String catalog, String schema, String tableName, char separator
     *                    eg: separator=.  catalog.schema.tableName
     */
    public static void addClassComment(InnerClass innerClass,
                                       DomainConfig domainConfig,
                                       String[] commoneLines) {
        if (GlobalConfig.getString("suppress.all.comments") != null) {
            return;
        }

        StringBuilder sb = new StringBuilder();

        innerClass.addJavaDocLine("/**"); //$NON-NLS-1$
        sb.append(" * " + domainConfig.getEntityClassCNName());
        innerClass.addJavaDocLine(sb.toString());
        sb.setLength(0);


        addCommentLine(innerClass, sb, commoneLines);

        sb.append(" * This class corresponds to the database table "); //$NON-NLS-1$
        sb.append(domainConfig.getFullyQualifiedTableText());
        innerClass.addJavaDocLine(sb.toString());
        sb.setLength(0);

        innerClass.addJavaDocLine(" *");

        sb.append(" * @Author ").append(GlobalConfig.getString("file.comment.author"));
        innerClass.addJavaDocLine(sb.toString());
        sb.setLength(0);

        sb.append(" * @Date ").append(GlobalConfig.getString("date.today"));
        innerClass.addJavaDocLine(sb.toString());

        addJavadocTag(innerClass, false);

        innerClass.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    private static void addCommentLine(JavaElement je, StringBuilder sb, String[] commoneLines) {
        if (commoneLines != null && commoneLines.length > 0) {
            for (String line : commoneLines) {
                sb.append(" * ").append(line);
                je.addJavaDocLine(sb.toString());
                sb.setLength(0);
            }
        }
    }
    public static void addJavaComment(JavaElement javaElement,
                                      DomainConfig domainConfig) {
        addJavaComment(javaElement, domainConfig, null);
    }

    /**
     *
     * @param innerClass
     * @param domainConfig String catalog, String schema, String tableName, char separator
     *                    eg: separator=.  catalog.schema.tableName
     */
    public static void addJavaComment(JavaElement innerClass,
                                       DomainConfig domainConfig,
                                       String[] commoneLines) {
        if (GlobalConfig.getString("suppress.all.comments") != null) {
            return;
        }

        StringBuilder sb = new StringBuilder();

        innerClass.addJavaDocLine("/**"); //$NON-NLS-1$
        sb.append(" * " + domainConfig.getEntityClassCNName());
        innerClass.addJavaDocLine(sb.toString());
        sb.setLength(0);


        addCommentLine(innerClass, sb, commoneLines);

        sb.append(" * This class corresponds to the database table "); //$NON-NLS-1$
        sb.append(domainConfig.getFullyQualifiedTableText());
        innerClass.addJavaDocLine(sb.toString());
        sb.setLength(0);

        innerClass.addJavaDocLine(" *");

        sb.append(" * @Author ").append(GlobalConfig.getString("file.comment.author"));
        innerClass.addJavaDocLine(sb.toString());
        sb.setLength(0);

        sb.append(" * @Date ").append(GlobalConfig.getString("date.today"));
        innerClass.addJavaDocLine(sb.toString());

        addJavadocTag(innerClass, false);

        innerClass.addJavaDocLine(" */"); //$NON-NLS-1$
    }



    /**
     *
     * @param innerClass
     * @param domainConfig String catalog, String schema, String tableName, char separator
     *                    eg: separator=.  catalog.schema.tableName
     */
    public static void addClassComment(InnerClass innerClass,
                                DomainConfig domainConfig) {
        addClassComment(innerClass, domainConfig, null);
    }

    public static void addEnumComment(InnerEnum innerEnum,
                               DomainConfig domainConfig) {
        if (GlobalConfig.getString("suppress.all.comments") != null) {
            return;
        }

        StringBuilder sb = new StringBuilder();

        innerEnum.addJavaDocLine("/**"); //$NON-NLS-1$
        innerEnum
                .addJavaDocLine(" * This enum was generated by MyBatis Generator."); //$NON-NLS-1$

        sb.append(" * This enum corresponds to the database table "); //$NON-NLS-1$
        sb.append(domainConfig.getFullyQualifiedTableText());
        innerEnum.addJavaDocLine(sb.toString());

        addJavadocTag(innerEnum, false);

        innerEnum.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    public static void addFieldComment(Field field,
                                       DomainField domainField,
                                       String[] commoneLines) {
        if (GlobalConfig.getString("suppress.all.comments") != null) {
            return;
        }

        StringBuilder sb = new StringBuilder();

        field.addJavaDocLine("/**"); //$NON-NLS-1$

        sb.append(" * "); //$NON-NLS-1$
        if (!StringUtil.isBLank(domainField.getFieldComment())) {
            sb.append(domainField.getFieldComment());
        } else if (!StringUtil.isBLank(domainField.getFieldCNName())) {
            sb.append(domainField.getFieldCNName());
        } else {
            sb.append(domainField.getColumnName());
        }
        field.addJavaDocLine(sb.toString());
        sb.setLength(0);

        addCommentLine(field, sb, commoneLines);

        sb.append(" * "); //$NON-NLS-1$
        sb.append(domainField.getDomainConfig().getFullyQualifiedTableText());
        sb.append('.');
        sb.append(domainField.getColumnName());
        field.addJavaDocLine(sb.toString());

        addJavadocTag(field, false);

        field.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    public static void addFieldComment(Field field,
                                DomainField domainField) {
        addFieldComment(field, domainField, null);
    }

    public static void addGeneralMethodComment(Method method,
                                        DomainConfig domainConfig) {
        if (GlobalConfig.getString("suppress.all.comments") != null) {
            return;
        }

        StringBuilder sb = new StringBuilder();

        method.addJavaDocLine("/**"); //$NON-NLS-1$
        method
                .addJavaDocLine(" * This method was generated by MyBatis Generator."); //$NON-NLS-1$

        sb.append(" * This method corresponds to the database table "); //$NON-NLS-1$
        sb.append(domainConfig.getFullyQualifiedTableText());
        method.addJavaDocLine(sb.toString());

        addJavadocTag(method, false);

        method.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    public static void addGetterComment(Method method,
                                        DomainField domainField,
                                        String[] commoneLines) {
        if (GlobalConfig.getString("suppress.all.comments") != null) {
            return;
        }

        StringBuilder sb = new StringBuilder();

        method.addJavaDocLine("/**"); //$NON-NLS-1$

        sb.append(" * "); //$NON-NLS-1$
        if (!StringUtil.isBLank(domainField.getFieldComment())) {
            sb.append(domainField.getFieldComment());
        } else if (!StringUtil.isBLank(domainField.getFieldCNName())) {
            sb.append(domainField.getFieldCNName());
        } else {
            sb.append(domainField.getColumnName());
        }
        method.addJavaDocLine(sb.toString());
        sb.setLength(0);

        addCommentLine(method, sb, commoneLines);

        method.addJavaDocLine(" *"); //$NON-NLS-1$

        sb.setLength(0);
        sb.append(" * @return the value of "); //$NON-NLS-1$
        sb.append(domainField.getDomainConfig().getFullyQualifiedTableText());
        sb.append('.');
        sb.append(domainField.getColumnName());
        method.addJavaDocLine(sb.toString());

        addJavadocTag(method, false);

        method.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    public static void addGetterComment(Method method,
                                 DomainField domainField) {
        addGetterComment(method, domainField, null);
    }

    public static void addSetterComment(Method method,
                                        DomainField domainField,
                                        String[] commoneLines) {
        if (GlobalConfig.getString("suppress.all.comments") != null) {
            return;
        }

        StringBuilder sb = new StringBuilder();

        method.addJavaDocLine("/**"); //$NON-NLS-1$
        sb.append(" * "); //$NON-NLS-1$
        if (!StringUtil.isBLank(domainField.getFieldComment())) {
            sb.append(domainField.getFieldComment());
        } else if (!StringUtil.isBLank(domainField.getFieldCNName())) {
            sb.append(domainField.getFieldCNName());
        } else {
            sb.append(domainField.getColumnName());
        }
        method.addJavaDocLine(sb.toString());
        sb.setLength(0);

        addCommentLine(method, sb, commoneLines);

        method.addJavaDocLine(" *"); //$NON-NLS-1$

        Parameter parm = method.getParameters().get(0);
        sb.setLength(0);
        sb.append(" * @param "); //$NON-NLS-1$
        sb.append(parm.getName());
        sb.append(" the value for "); //$NON-NLS-1$
        sb.append(domainField.getDomainConfig().getFullyQualifiedTableText());
        sb.append('.');
        sb.append(domainField.getColumnName());
        method.addJavaDocLine(sb.toString());

        addJavadocTag(method, false);

        method.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    public static void addSetterComment(Method method,
                                 DomainField domainField) {
        addSetterComment(method, domainField, null);
    }

    public static void addClassComment(InnerClass innerClass,
                                DomainConfig domainConfig,
                                boolean markAsDoNotDelete) {
        if (GlobalConfig.getString("suppress.all.comments") != null) {
            return;
        }

        StringBuilder sb = new StringBuilder();

        innerClass.addJavaDocLine("/**"); //$NON-NLS-1$
        innerClass
                .addJavaDocLine(" * This class was generated by MyBatis Generator."); //$NON-NLS-1$

        sb.append(" * This class corresponds to the database table "); //$NON-NLS-1$
        sb.append(domainConfig.getFullyQualifiedTableText());
        innerClass.addJavaDocLine(sb.toString());

        addJavadocTag(innerClass, markAsDoNotDelete);

        innerClass.addJavaDocLine(" */"); //$NON-NLS-1$
    }
}
